spring.application.name=worker-service
server.port=8081

#Please remove this error message showing, that's only for the testing purpose
spring.web.error.include-message=always

spring.datasource.url=jdbc:postgresql://localhost:5434/taskforge
spring.datasource.username=postgres
spring.datasource.password=Malith10a
spring.jpa.hibernate.ddl-auto=none

#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

spring.data.redis.host=localhost
spring.data.redis.port=6379


